[global]
log_level = 'trace'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'evmos_9001-2'
rpc_addr = 'http://evmos:26657'
grpc_addr = 'http://evmos:9090'
websocket_addr = 'ws://evmos:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'evmos'
key_name = 'mykey'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.0001, denom = 'aevmos' }
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }

[[chains]]
id = 'stride-1'
rpc_addr = 'http://stride:26657'
grpc_addr = 'http://stride:9090'
websocket_addr = 'ws://stride:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'ustrd'
key_name = 'mykey'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.0001, denom = 'aevmos' }
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

